spring:
  application:
    name: ms-greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
ms-greeting-service:
  greeting: "Cia"
  default-value: "Mundo"
